### ISSUE TITLE
Missing binary /usr/bin/connecttox

### ISSUE THREAD

**Issue by vmoravec** [yast/yast-certify#1]
I have tested this yast module on openSuse 12.3 and after it's been started it showed error: 
`You must run this from X`. This is shown even if I start the module in gui mode.

It expects the binary /usr/bin/connecttox , the dependencies provide no such file and it is also not delivered with the base system.

**Comment by vmoravec** [comment]
Recorded in bzilla: https://bugzilla.novell.com/show_bug.cgi?id=827593

**Comment by cwh42** [comment]
The bug in bugzilla got closed with this message: "This thing is dead. It was last updated 2004 and was never in any product."
